- name: create MongoDB admin user
  mongodb_user:
    user={{ mongodb_admin.username }}
    password={{ mongodb_admin.password }}
    database=admin
    roles={{ mongodb_admin.roles | join(',') }}
  changed_when: false
  ignore_errors: true
  when: mongodb_admin.username and mongodb_admin.password

- name: generate ~/.mongorc.js
  template:
    src=mongorc.js.j2
    dest=~/.mongorc.js
    mode=0644
  when: mongodb_admin.username and mongodb_admin.password
